# Site
title: Justworks Group
email: lthibes@justworksgroup.com.br
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# Site

# Blog
permalink: /:title.html
future   : false
# Blog

# Social
social_whatsapp: https://github.com/justworksgroup
social_github  : https://github.com/justworksgroup
social_linkedin: https://github.com/justworksgroup
# Social

# Build
exclude:
    - docs
    - styles
    - CNAME
    - Makefile
    - README.md
    - package.json
    - package-lock.json
    - tailwind.config.js

# Build
