# Site
title: Justworks Group
email: contato@justworksgroup.com.br
phone: (11) 12345-6789
# Site

# Blog
permalink: /:title.html
future   : false
# Blog

# Social
social_whatsapp: https://github.com/justworksgroup
social_github  : https://github.com/justworksgroup
social_linkedin: https://github.com/justworksgroup
# Social

# Build
exclude:
    - docs
    - styles
    - CNAME
    - Makefile
    - README.md
    - package.json
    - package-lock.json
    - tailwind.config.js

# Build
